### ISSUE TITLE
Add Slurm usage table

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/keystone-api#116]
We will need to track allocation usage across the cluster. This will require a new DB table. I propose the following fields:

- allocation (foreign key, indexed)
- user/account (foreign key, indexed)
- usage (int)

Alternatively, we can explore extending the allocation table if we only want to track usage by account.

**Comment by djperrefort** [comment]
@Comeani can we support per user usage with the API or are we limited to the account level only.

**Comment by Comeani** [comment]
@djperrefort I've spent some more time with the API in the context of the restricted env login node (Troy and Sasha are still working on enabling the full functionality for Teach and the other clusters). 

The usage value under the associations endpoint does not seem to change when I submit jobs... I can find `billing_tres` in the jobs endpoint in the reference, but am not seeing that in the output coming from the restricted node's slurmrestd (this may be due to us using the v3 openapi specification). Basically it's currently looking like we can't actually get a summary usage value out of the rest api, and might be in for a decent amount of work constructing it from each individual job's info (if we don't otherwise resort to wrapping something like sreport). 

I've also been staring at my computer all day so I think doing more research tomorrow (and honestly just sending a ticket to schedmd) with fresh eyes will help.

**Comment by djperrefort** [comment]
> I can find billing_tres in the jobs endpoint in the reference, but am not seeing that in the output coming from the restricted node's slurmrestd (this may be due to us using the v3 openapi specification).

I'm not sure what you mean by this. Are you saying the API behavior does not match the API spec? Specifically, I'm not clear what OpenAPI v3 has to do with the issue.

I agree we should follow up with SchedMD. Can you please reach out to Nick at SchedMD directly and CC @chnixi and I?

**Comment by Comeani** [comment]
Sorry, I think I meant that the value is present in the v0.0.40 reference, but it does not show up in the v0.0.38 output. I got my wires crossed on the OpenAPI version and the SLURM OpenAPI DB version. I'm not sure how coupled the db version and the SLURM release version are, I can include a question about that in my email to Nick.
